DROP DATABASE IF EXISTS TheDrifters;
CREATE DATABASE TheDrifters;

DROP TABLE IF EXISTS TheDrifters.FlatType;
CREATE TABLE TheDrifters.FlatType(
	FlatTypeID INT NOT NULL AUTO_INCREMENT Primary KEY, 
	Type VARCHAR(255) ,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT
);

DROP TABLE IF EXISTS TheDrifters.StoreyRange;
CREATE TABLE TheDrifters.StoreyRange(
	StoreyRangeID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	StoreyRange VARCHAR(255),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT
);

DROP TABLE IF EXISTS TheDrifters.FlatModel;
CREATE TABLE TheDrifters.FlatModel(
	FlatModelID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Model VARCHAR(255),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT
);

DROP TABLE IF EXISTS TheDrifters.Town;
CREATE TABLE TheDrifters.Town(
	TownID INT NOT NULL AUTO_INCREMENT Primary KEY,
	Name VARCHAR(255),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT
);

DROP TABLE IF EXISTS TheDrifters.StreetName;
CREATE TABLE TheDrifters.StreetName(
	StreetNameID INT NOT NULL AUTO_INCREMENT Primary KEY,
	Name VARCHAR(255),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT,
	TownID INT,
	FOREIGN KEY(TownID) REFERENCES Town(TownID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TheDrifters.ResaleHdb;
CREATE TABLE TheDrifters.ResaleHdb(
	ResaleHdbID INT NOT NULL AUTO_INCREMENT Primary KEY,
	Block VARCHAR(5),
	FloorArea INT,
    PostalCode VARCHAR(6),
    Latitude DOUBLE,
    Longitude DOUBLE,
	LeaseCommenceDate YEAR,
	LeaseEndDate YEAR,
	ResalePrice FLOAT,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT,
	StreetNameID INT,
	FlatTypeID INT,
	StoreyRangeID INT,
	FlatModelID INT,
	FOREIGN KEY(StreetNameID) REFERENCES StreetName(StreetNameID) ON DELETE CASCADE,
	FOREIGN KEY(FlatTypeID) REFERENCES FlatType(FlatTypeID) ON DELETE CASCADE,
	FOREIGN KEY(StoreyRangeID) REFERENCES StoreyRange(StoreyRangeID) ON DELETE CASCADE,
	FOREIGN KEY(FlatModelID) REFERENCES FlatModel(FlatModelID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TheDrifters.User;
CREATE TABLE TheDrifters.User(
	UserID INT NOT NULL AUTO_INCREMENT Primary KEY,
	Name VARCHAR(255),
	Email VARCHAR(255),
	Password VARCHAR(255),
	Salt VARCHAR(255),
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INT,
	UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP,
	UpdatedBy INT
);